version: 1

config:
    slack_notify: true
    slack_channel: 'mkp-pipeline-deploy'
    dev_branch_name: dev

jobs:
    build_docker:
        steps:
            - build_image:
                dockerfile: Dockerfile.dev

    publish_docker:
        steps:
            - push_image


    deploy_dev:
        steps:
            - deploy_dev:
                  cluster: marketplace
                  workload: open-api-docs
                  has_worker: 'no'

workflows:
    jenkins_pipeline:
        jobs:
            - build_docker
            - publish_docker:
                  requires:
                      - build_docker
                  filters:
                      branches:
                          only:
                              - master
                              - dev
                              - staging

            - deploy_dev:
                  requires:
                      - publish_docker
                  filters:
                      branches:
                          only:
                              - dev
